import Image from "next/image";
import { Fragment, useEffect, useState } from "react";
import imagen5 from "../public/Img/imagen_3.jpg";
import estilos from "../styles/secion1.module.css";
import Head from "next/head";

function Secion5 (){


   

    return(
        <Fragment>

        <Head>
        <title>Secion 5</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={estilos.container}> 

        <div className={estilos.contenedor_titulo}>
        <Image
        src={imagen5}
        alt="Picture of the author"
        width={500}
        height={500}
       
        
      />
      </div>


      <div className={estilos.parrafo}>
      <h1>Secion 5</h1>
      <p>Nuestra cadena productiva contribuye a preservar un área equivalente a 10 veces el tamaño de Bogotá. Un área que tiene un total de 24.788 personas involucradas, con quienes trabajamos en red. Que privilegia la agricultura familiar y el uso racional de los recursos renovables. Una producción de impacto ambiental y social positivo que genera beneficios para las personas y la selva.</p>
      <br></br>
      <p>Estudia los activos de la biodiversidad brasileña para crear productos con beneficios comprobados, que proporcionan placer, bienestar y que despiertan tus sentidos.
       Natura Ekos desarrolla productos de cuidado personal que preservan la selva manteniéndola en pie, valorizando el conocimiento tradicional de comunidades locales y el patrimonio genético de los bioactivos. Para eso, compartimos con las comunidades las ganancias originadas de los ingredientes recolectados por ellas.Ekos, vive la biobelleza.
      </p>

      <p>Somos cosmética de alto desempeño que potencia ingredientes naturales y vegetales de la Amazonía, con tecnología verde que cuida el medio ambiente. Somos sustentables y regeneramos la vida en la selva y quienes viven en ella. Al elegir Natura Ekos contribuyes con la conservación de 1,8 millones de hectáreas de selva y a fortalecer los ingresos de 6 mil familias de la Amazonía.</p>

<h2>Nueva fórmula:</h2>
<p>Hasta 3 veces más potente con más concentración de bioactivos brutos del amazonas. Cada activo un beneficio. 96% de ingredientes de origen natural y fórmula altamente vegetalizada. Biocompatible y altamente biodegradable. Sin parabenos, sin siliconas y sin oleos minerales.</p>
      </div>
     </div>
    </Fragment>
    );

}


export default Secion5;